In [15]:
import pandas as pd
import numpy as np

In [16]:
linkQ ='https://www1.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_queens.xlsx'
queens = pd.read_excel(linkQ, skiprows=4)
linkB ='https://www1.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_brooklyn.xlsx'
bkl = pd.read_excel(linkB, skiprows=4)
linkM ='https://www1.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_manhattan.xlsx'
manhattan = pd.read_excel(linkM, skiprows=4)
linkS ='https://www1.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_statenisland.xlsx'
si = pd.read_excel(linkS, skiprows=4)
linkBr ='https://www1.nyc.gov/assets/finance/downloads/pdf/rolling_sales/rollingsales_bronx.xlsx'
bronx = pd.read_excel(linkBr, skiprows=4)

In [17]:
queens = queens.drop(['EASEMENT', 'APARTMENT NUMBER','TAX CLASS AT PRESENT', 'BUILDING CLASS AT PRESENT'], axis=1)
bkl = bkl.drop(['EASEMENT', 'APARTMENT NUMBER','TAX CLASS AT PRESENT', 'BUILDING CLASS AT PRESENT'], axis=1)
manhattan = manhattan.drop(['EASEMENT', 'APARTMENT NUMBER','TAX CLASS AT PRESENT', 'BUILDING CLASS AT PRESENT'], axis=1)
si = si.drop(['EASEMENT', 'APARTMENT NUMBER','TAX CLASS AT PRESENT', 'BUILDING CLASS AT PRESENT'], axis=1)
bronx = bronx.drop(['EASEMENT', 'APARTMENT NUMBER','TAX CLASS AT PRESENT', 'BUILDING CLASS AT PRESENT'], axis=1)

In [19]:
queens['GROSS SQUARE FEET'].replace(0.0, np.nan,inplace=True)
queens['LAND SQUARE FEET'].replace(0.0, np.nan,inplace=True)
queens['TOTAL UNITS'].replace(0.0, np.nan,inplace=True)
queens['SALE PRICE'].replace(0.0, np.nan,inplace=True)
queens['YEAR BUILT'].replace(0.0, np.nan,inplace=True)
bkl['GROSS SQUARE FEET'].replace(0.0, np.nan,inplace=True)
bkl['LAND SQUARE FEET'].replace(0.0, np.nan,inplace=True)
bkl['TOTAL UNITS'].replace(0.0, np.nan,inplace=True)
bkl['SALE PRICE'].replace(0.0, np.nan,inplace=True)
bkl['YEAR BUILT'].replace(0.0, np.nan,inplace=True)
manhattan['GROSS SQUARE FEET'].replace(0.0, np.nan,inplace=True)
manhattan['LAND SQUARE FEET'].replace(0.0, np.nan,inplace=True)
manhattan['TOTAL UNITS'].replace(0.0, np.nan,inplace=True)
manhattan['SALE PRICE'].replace(0.0, np.nan,inplace=True)
manhattan['YEAR BUILT'].replace(0.0, np.nan,inplace=True)
si['GROSS SQUARE FEET'].replace(0.0, np.nan,inplace=True)
si['LAND SQUARE FEET'].replace(0.0, np.nan,inplace=True)
si['TOTAL UNITS'].replace(0.0, np.nan,inplace=True)
si['SALE PRICE'].replace(0.0, np.nan,inplace=True)
si['YEAR BUILT'].replace(0.0, np.nan,inplace=True)
bronx['GROSS SQUARE FEET'].replace(0.0, np.nan,inplace=True)
bronx['LAND SQUARE FEET'].replace(0.0, np.nan,inplace=True)
bronx['TOTAL UNITS'].replace(0.0, np.nan,inplace=True)
bronx['SALE PRICE'].replace(0.0, np.nan,inplace=True)
bronx['YEAR BUILT'].replace(0.0, np.nan,inplace=True)

In [20]:
queens = queens.dropna()
bkl = bkl.dropna()
manhattan = manhattan.dropna()
si = si.dropna()
bronx = bronx.dropna()

In [22]:
ny = pd.concat([queens, bkl, manhattan, si, bronx], ignore_index=True)

In [23]:
ny.to_csv('nyrolling

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,BLOCK,LOT,ADDRESS,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,AIRPORT LA GUARDIA,01 ONE FAMILY DWELLINGS,949,30,19-40 81ST SREET,11370.0,1.0,0.0,1.0,1800.0,1224.0,1945.0,1,A5,935000.0,2021-12-08
1,4,AIRPORT LA GUARDIA,01 ONE FAMILY DWELLINGS,949,34,19-48 81ST STREET,11370.0,1.0,0.0,1.0,1799.0,1224.0,1945.0,1,A5,864195.0,2022-07-15
2,4,AIRPORT LA GUARDIA,01 ONE FAMILY DWELLINGS,949,37,19-54 81ST STREET,11370.0,1.0,0.0,1.0,1799.0,1224.0,1945.0,1,A5,815000.0,2022-06-24
3,4,AIRPORT LA GUARDIA,01 ONE FAMILY DWELLINGS,976,60,21-23 80TH STREET,11370.0,1.0,0.0,1.0,1800.0,1224.0,1950.0,1,A5,900000.0,2022-02-08
4,4,AIRPORT LA GUARDIA,02 TWO FAMILY DWELLINGS,976,56,21-31 80TH STREET,11370.0,2.0,0.0,2.0,1800.0,1224.0,1950.0,1,B3,805000.0,2021-12-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31236,2,WOODLAWN,07 RENTALS - WALKUP APARTMENTS,3392,34,450 EAST 239 STREET,10470.0,6.0,0.0,6.0,3750.0,4600.0,1910.0,2,C5,955000.0,2021-12-16
31237,2,WOODLAWN,14 RENTALS - 4-10 UNIT,3376,58,4277 KATONAH AVENUE,10470.0,4.0,1.0,5.0,2125.0,3780.0,1930.0,2,S4,800000.0,2022-01-19
31238,2,WOODLAWN,22 STORE BUILDINGS,3377,59,4299 KATONAH AVENUE,10470.0,2.0,5.0,7.0,6000.0,8125.0,1931.0,4,K4,4100000.0,2021-12-07
31239,2,WOODLAWN,29 COMMERCIAL GARAGES,3374,1,235 EAST 233RD STREET,10470.0,0.0,1.0,1.0,3283.0,1160.0,1931.0,4,G1,930000.0,2021-12-10
31240,2,WOODLAWN,29 COMMERCIAL GARAGES,3395,63,4219 WEBSTER AVENUE,10470.0,0.0,1.0,1.0,10593.0,2574.0,1931.0,4,G1,3000000.0,2021-12-17